# Etapa de build
FROM node:22-alpine AS build

WORKDIR /frontend

COPY package*.json ./
COPY .postcssrc.json ./
COPY tsconfig*.json ./

RUN npm install -g @angular/cli && npm install

EXPOSE 4200

CMD ["ng","serve","--host","0.0.0.0", "--poll", "100"]
