services:
  backend:
    build: 
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: challenge-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - challenge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: challenge-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - challenge-network

  postgres:
    image: postgres:15
    container_name: godlevel-db
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U challenge -d challenge_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - challenge-network

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: godlevel-data-gen
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://challenge:challenge_2024@postgres:5432/challenge_db
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        echo 'Generating challenge data...' &&
        python generate_data.py --db-url postgresql://challenge:challenge_2024@postgres:5432/challenge_db
      "
    profiles:
      - initialization
    networks:
      - challenge-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: godlevel-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@godlevel.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    profiles:
      - debug
    networks:
      - challenge-network

volumes:
  postgres_data:
    driver: local

networks:
  challenge-network:
    driver: bridge

